services:
  fess01:
    image: ghcr.io/codelibs/fess:14.18.0
    container_name: fess01
    environment:
      - "SEARCH_ENGINE_HTTP_URL=http://search01:9200"
      - "FESS_DICTIONARY_PATH=${FESS_DICTIONARY_PATH:-/usr/share/opensearch/config/dictionary/}"
      - "FESS_JAVA_OPTS=-Dfess.config.crawler.document.cache.enabled=false -Dfess.config.adaptive.load.control=0 -Dfess.config.query.additional.response.fields=searcher -Dfess.config.index.user.initial_password=admin"
#      - "FESS_LOG_LEVEL=debug"
    ports:
      - "8080:8080"
    networks:
      - semantic_net
    volumes:
      - ./data/fess/opt/fess:/opt/fess
      - ./data/fess/var/lib/fess:/var/lib/fess
      - ./data/fess/var/log/fess:/var/log/fess
      - ./data/fess/usr/share/fess/app/WEB-INF/plugin:/usr/share/fess/app/WEB-INF/plugin
      - ./data/fess/usr/share/fess/app/WEB-INF/view/semantic:/usr/share/fess/app/WEB-INF/view/semantic
    depends_on:
      - search01
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: unless-stopped

  search01:
    image: ghcr.io/codelibs/fess-opensearch:2.18.0
    container_name: search01
    environment:
      - node.name=search01
      - discovery.seed_hosts=search01
      - cluster.initial_cluster_manager_nodes=search01
      - cluster.name=fess-search
      - bootstrap.memory_lock=true
      - node.roles=cluster_manager,data,ingest,ml
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "FESS_DICTIONARY_PATH=/usr/share/opensearch/config/dictionary"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - ./data/opensearch/usr/share/opensearch/data:/usr/share/opensearch/data
      - ./data/opensearch/usr/share/opensearch/config/dictionary:/usr/share/opensearch/config/dictionary
    ports:
      - 9200:9200
    networks:
      - semantic_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: unless-stopped

networks:
  semantic_net:
    driver: bridge
